### PR TITLE
KeyboardEvent-MultiDecoder

### PR DESCRIPTION
**Pull request by manuscrypt**
Hi Ohanhi

This is my first PR ever, just to let it be known.

I added a file called `EventDecoder.elm` and made an extra sample.

You have seen this before, it's not ready for production use, but it might help when working this problem out. 

I am also not 100% certain, that the order in which the Decoders are applied, is fully correct.

I hope you can use this in one form or another.
Cheers!

### CODE REVIEW

**Comment by ohanhi** [comment]
Hi @ManuScriptHub!

Sorry for the really slow response, I happened to look at this PR during my summer vacation and promptly forgot about it. My sincere apologies.

I just upgraded the master branch for the upcoming 0.18 and started to look at how your work could be integrated to it. I then realized my code and your code have virtually no common ground, apart from being keyboard input handling. The `BestGuessKey` logic is pretty cool, though, so it would be nice to have it out in the open. So what do you think about releasing the code as a separate package under your own name?

**Comment by ohanhi** [comment]
By the way, I uploaded my version of your branch, upgraded to 0.18: https://github.com/ohanhi/keyboard-extra/tree/ManuScriptHub-master

**Comment by manuscrypt** [comment]
Hi ohanhi

We all are crazy busy, it seems, so there is really no need to apologize.

I wrote the code because of the very different behaviour between Edge, FF
and Chrome when dealing with character key codes.
In the end, I ditched it and used a Textbox :)

So, I don't care too much about the code anymore, you can just remove it as
I agree that it does not belong there.

Thanks for the good work, I'll be checking out native soon. (Yay, Luke!)

Cheerio
Manuel

**Comment by ohanhi** [comment]
All right, closing the PR in mutual agreement then! :)

**Pull request closed without merging**
